### ISSUE TITLE
Afficher l'objet parlementaire associé à un évènement dans la page des évènements

### ISSUE THREAD

**Issue by rufener** [sitn/ne_sop#22]
Ajouter une référence à l'objet parlementaire (év. readonly).

![image](https://github.com/sitn/ne_sop/assets/7292688/2b2a8bf9-a95d-423b-aa71-94d039c1f8b8)

**Comment by mparkan** [comment]
Fixed, Item number, name and hyperlink are now displayed at the top of the Event form.
