### ISSUE TITLE
Fix sorting of date (and compound) columns in tables (items, entities, events)

### ISSUE THREAD

**Issue by mparkan** [sitn/ne_sop#82]

**Comment by rufener** [comment]
Seems to work on my side (firefox, french language)

**Comment by rufener** [comment]
> Seems to work correctly on my side (firefox, french language)

Le bug est reproduit sur le tableau des items pour les dates de dépot et du délai de retour au secrétariat général

**Comment by mparkan** [comment]
Fixed
